### ISSUE TITLE
Error on debian

### ISSUE THREAD

**Issue by zsozso** [mikey-austin/greyd#2] opened 2015-02-28 10:33 UTC
/usr/local/bin/greyd: symbol lookup error: /usr/local/lib/greyd/greyd_netfilter.so: undefined symbol: nfct_nlmsg_build

cat /etc/debian_version 
7.8

installed packages:

[1047] > dpkg --get-selections | grep -v deinstall | grep netfilter
libnetfilter-conntrack-dev			install
libnetfilter-conntrack3:amd64			install
libnetfilter-log-dev				install
libnetfilter-log1				install

[1048] > dpkg --get-selections | grep -v deinstall | grep libip
libipset-dev					install
libipset2:amd64					install
libiptcdata0					install
libiptcdata0-dev				install

[1049] > dpkg --get-selections | grep -v deinstall | grep libcap
libcap-dev:amd64				install
libcap-ng0					install
libcap2:amd64					install
libcap2-bin					install
[root@debian /var/src/greyd-0.6.1]

nm -D  /usr/lib/x86_64-linux-gnu/libnetfilter_conntrack.so.3 | grep nfct_     
0000000000006400 T nfct_attr_grp_is_set
00000000000064c0 T nfct_attr_grp_unset
0000000000006130 T nfct_attr_is_set
0000000000006190 T nfct_attr_is_set_array
0000000000006240 T nfct_attr_unset
0000000000006530 T nfct_build_conntrack
00000000000065b0 T nfct_build_query
0000000000005c40 T nfct_callback_register
0000000000005d90 T nfct_callback_register2
0000000000005d20 T nfct_callback_unregister
0000000000005e60 T nfct_callback_unregister2
00000000000067c0 T nfct_catch
0000000000005a90 T nfct_clone
0000000000005470 T nfct_close
00000000000068d0 T nfct_cmp
0000000000006870 T nfct_compare
0000000000006930 T nfct_copy
0000000000006c10 T nfct_copy_attr
0000000000005a00 T nfct_destroy
0000000000005520 T nfct_fd
0000000000006ce0 T nfct_filter_add_attr
0000000000006d80 T nfct_filter_add_attr_u32
0000000000006df0 T nfct_filter_attach
0000000000006ca0 T nfct_filter_create
0000000000006cb0 T nfct_filter_destroy
0000000000006e20 T nfct_filter_detach
0000000000006e50 T nfct_filter_dump_create
0000000000006e60 T nfct_filter_dump_destroy
0000000000006e90 T nfct_filter_dump_set_attr
0000000000006f30 T nfct_filter_dump_set_attr_u8
0000000000006da0 T nfct_filter_set_logic
0000000000005fe0 T nfct_get_attr
0000000000006310 T nfct_get_attr_grp
00000000000060b0 T nfct_get_attr_u16
00000000000060e0 T nfct_get_attr_u32
0000000000006100 T nfct_get_attr_u64
0000000000006080 T nfct_get_attr_u8
0000000000005bf0 T nfct_getobjopt
0000000000005a80 T nfct_maxsize
00000000000059d0 T nfct_new
0000000000005530 T nfct_nfnlh
0000000000005400 T nfct_open
0000000000005310 T nfct_open_nfnl
00000000000065c0 T nfct_parse_conntrack
00000000000066a0 T nfct_query
0000000000006730 T nfct_send
0000000000005ed0 T nfct_set_attr
00000000000062a0 T nfct_set_attr_grp
0000000000005f80 T nfct_set_attr_u16
0000000000005fa0 T nfct_set_attr_u32
0000000000005fc0 T nfct_set_attr_u64
0000000000005f60 T nfct_set_attr_u8
0000000000005ba0 T nfct_setobjopt
0000000000005a50 T nfct_sizeof
00000000000067f0 T nfct_snprintf

**Comment by mikey-austin** [comment] 2015-02-28 11:30
Thanks for the report. It looks like the libnetfilter-conntrack-dev package in wheezy is version 1.0.1, and is missing some symbols.

I'm running it on a few Scientific Linux 6 machines with version 1.0.4:

$ nm -D /usr/local/lib/libnetfilter_conntrack.so.3 |grep nlmsg
                 U mnl_nlmsg_get_payload
000000000000c130 T nfct_nlmsg_build
000000000000bd70 T nfct_nlmsg_parse
00000000000138c0 T nfexp_nlmsg_build
00000000000139e0 T nfexp_nlmsg_parse

That's annoying. So as it stands, it won't work out of the box on Debian until Jessie which has 1.0.4.

What do you reckon?

**Comment by mikey-austin** [comment] 2015-02-28 11:49
See commit 6cdec0fbc45b4e98f2ff5bed1b7d44146f1d06a6. The configure will now fail if trying to build with a version of libnetfilter_conntrack without nfct_nlmsg_build (< 1.0.4).

**Comment by zsozso** [comment] 2015-03-02 05:30
Thanks for your reply. 
I've changed to testing repo for the libnetfilter. 

Unfortunately I have another problem on debian.
After half day running the greyd process used 99% CPU. I killed the process with SIGTERM, but I got 2 other errors:
1: 
Lock table is out of available lock entriesgreyd[28963]: listening for incoming connections
greyd[28961]: db open (greyd.db) failed: Cannot allocate memory
Database handles still open at environment close
greyd[28963]: could not unlink /usr/local/var/run/greyd.pid: No such file or directory
greyd[28962]: stopping firewall process


2: After "db_recover -c -v" command:
Finding last valid log LSN: file: 3 offset 7519318
Recovery starting from [1][28]
Recovery complete at Mon Mar  2 06:22:13 2015
Maximum transaction ID 8000f4ad Recovery checkpoint [3][7519318]

Lock table is out of available lock entries
greyd[30291]: Error deleting current record: Cannot allocate memory
greyd[30293]: could not unlink /usr/local/var/run/greyd.pid: No such file or directory
greyd[30292]: stopping firewall process 

Version:
db_recover -V 
Berkeley DB 5.1.29: (October 25, 2011)

**Comment by mikey-austin** [comment] 2015-03-02 07:08
I used to see the high CPU usage in the early days when a child process died unexpectedly, and parent poll() listening on the other end of the pipe didn't check for an error. I'm running it on a Debian machine now, and this is the normal process layout:

<pre>$ ps axuwf |grep [g]rey
greydb    4077  0.0  0.0  40852  2044 ?        Ss   17:56   0:00 greyd
greyd     4078  0.0  0.0  39368  1324 ?        S    17:56   0:00  \_ greyd
greyd     4079  0.0  0.2  46384  4208 ?        S    17:56   0:00  \_ greyd
greydb    4080  0.0  0.0  40852  1676 ?        S    17:56   0:00  \_ greyd
greydb    4149  0.0  0.1  42876  2060 ?        Ss   17:56   0:00 greylogd</pre>

As for the database issues, it appears that some processes died with open environment handles and/or corrupted the database. Let's try and catch the CPU usage issue first.

A couple more things:

1. What does your greyd.conf look like?

2. I just noticed the default config has "chroot" enabled, and the greyd PID file is sitting outside it (which is wrong). If chrooting, you need to make sure that *greyd_pidfile* is contained within the *chroot_dir*, and the main user has permissions to remove it, ie:

<pre>chroot_dir = "/var/empty/greyd"
greyd_pidfile = "/var/empty/greyd/greyd.pid"</pre>

The default config can be cleaned up a tad.

**Comment by zsozso** [comment] 2015-03-02 09:40
Here is mine:
greydb    8945  0.0  0.2  47168  2052 ?        Ss   10:31   0:00 /usr/local/sbin/greyd -G 5:4:864 -w 1 -f /usr/local/etc/greyd/greyd.conf
greyd     8946  0.0  0.1  45684  1392 ?        S    10:31   0:00  \_ /usr/local/sbin/greyd -G 5:4:864 -w 1 -f /usr/local/etc/greyd/greyd.conf
greyd     8947  0.0  0.4  52700  4240 ?        S    10:31   0:00  \_ /usr/local/sbin/greyd -G 5:4:864 -w 1 -f /usr/local/etc/greyd/greyd.conf
greydb    8948  0.0  0.1  47168  1748 ?        S    10:31   0:00  \_ /usr/local/sbin/greyd -G 5:4:864 -w 1 -f /usr/local/etc/greyd/greyd.conf
greydb    8950  0.0  0.2  49192  2120 ?        Ss   10:31   0:00 /usr/local/sbin/greylogd -f /usr/local/etc/greyd/greyd.conf

The config is now almost default, except spamcop list(apprx. 86000 lines). Now I've put pid file into chroot dir.
You can look into this: http://pastebin.com/Wg6S53YQ

**Comment by mikey-austin** [comment] 2015-03-02 22:15
Ok ,that all looks normal so far. If it happens again, before killing, could you please record the same output above so that I can see which child process died? I need a bit more info to go on. I suspect it is due to a corrupted database.

Also as a side note, in your config, the whitelist should be specified after all of the blacklists in the "lists" parameter, as entries in the whitelist get subtracted from proceeding blacklists. I just updated the default config with this information.

**Comment by zsozso** [comment] 2015-03-04 07:41
Well, I'm sure there is some error on debian.

Yesterday, after 1 hour ran the greyd process stopped responding. I could reproduce twice but I don't know what happened exactly. 
After kill&restart the db files got corrupted.  

The debug output didn't show anything strange, just stopped printing and (working).  Before that there was 500-700 concurrent connections to greyd process.

**Comment by zsozso** [comment] 2015-03-04 08:31
I found it :)
How can I fix it? 

Mar  4 08:54:52 debian kernel: [312931.469532] nf_conntrack: table full, dropping packet.
Mar  4 08:54:52 debian kernel: [312931.472582] nf_conntrack: table full, dropping packet.
Mar  4 08:54:52 debian kernel: [312931.474541] nf_conntrack: table full, dropping packet.
Mar  4 08:54:55 debian kernel: [312935.181799] net_ratelimit: 23 callbacks suppressed
Mar  4 08:54:55 debian kernel: [312935.181801] nf_conntrack: table full, dropping packet.
Mar  4 08:54:55 debian kernel: [312935.186102] nf_conntrack: table full, dropping packet.

**Comment by mikey-austin** [comment] 2015-03-04 08:31
Those are decent numbers. Are you using greyd in production, or are you stress testing yourself? I'd like to try and reproduce this one so I can fix it. 

I will try to simulate that many connections and see if i can crash it.

-------- Original message --------

**Comment by zsozso** [comment] 2015-03-04 08:40
No stress test, just on a backup mx server (big domain). 
I think I can limit up the the hash table or /proc/sys/net/ipv4/netfilter/ip_conntrack_max but I guess it is only temporay solution. 
I'm not sure, but the conntract table is just increasing and nothing get out. Am I wrong?

**Comment by zsozso** [comment] 2015-03-04 10:02
In the meantime I've again high CPU usage.

Here was the normal state:
greydb    8950  0.1  0.2  49192  2116 ?        Ss   Mar02   3:47 /usr/local/sbin/greylogd -f /usr/local/etc/greyd/greyd.conf
greydb   21941  0.0  0.3  47172  2764 ?        Ss   08:57   0:00 /usr/local/sbin/greyd -G 5:4:864 -w 1 -f /usr/local/etc/greyd/greyd.conf
greyd    21942 20.4  0.1  45684  1628 ?        S    08:57   6:14  \_ /usr/local/sbin/greyd -G 5:4:864 -w 1 -f /usr/local/etc/greyd/greyd.conf
greyd    21943  5.1  3.1 6110956 28524 ?       S    08:57   1:34  \_ /usr/local/sbin/greyd -G 5:4:864 -w 1 -f /usr/local/etc/greyd/greyd.conf
greydb   21944  0.1  0.2  47172  2676 ?        S    08:57   0:02  \_ /usr/local/sbin/greyd -G 5:4:864 -w 1 -f /usr/local/etc/greyd/greyd.conf


Now:
ps axuwf |grep [g]rey
greydb    8950  0.1  0.2  49192  2116 ?        Ss   Mar02   3:48 /usr/local/sbin/greylogd -f /usr/local/etc/greyd/greyd.conf
greydb   21944 23.5  0.3  47172  2772 ?        R    08:57  28:25 /usr/local/sbin/greyd -G 5:4:864 -w 1 -f /usr/local/etc/greyd/greyd.conf

top:
  PID USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND                                                                                              
21944 greydb    20   0 47172 2772 2104 R  99.9  0.3  30:07.38 greyd 

strace -p 21944: 
read(7, "", 4096)                       = 0
read(7, "", 4096)                       = 0
read(7, "", 4096)                       = 0
read(7, "", 4096)                       = 0
read(7, "", 4096)                       = 0
...

/var/log/messages:
Mar  4 08:59:03 debian kernel: [313183.060192] TCP: Possible SYN flooding on port 8025. Sending cookies.  Check SNMP counters.
Mar  4 09:32:10 debian kernel: [315169.594606] The scan_unevictable_pages sysctl/node-interface has been disabled for lack of a legitimate use case.  If you have one, please send an email to linux-mm@kvack.org.

**Comment by mikey-austin** [comment] 2015-03-04 10:08
Ok that's starting to make more sense. I think the answer is in the conntrack tuning here. Greyd will keep each connection around for roughly 30 to 60 seconds (for grey listed connections) and blacklisted around even up to 300 seconds, so it will be heavier on conntrack then other programs.

-------- Original message --------

**Comment by mikey-austin** [comment] 2015-03-04 11:26
Thanks for all of your info. Regarding the CPU issue, the reason is the greylisting "reader" process is blocking waiting for grey data from the main process, but the main process has died unexpectedly, and as a result reading from the pipe is returning 0 straight away, sending it into an infinite loop.

I have fixed this in commit 716ec51. I was able to reproduce this behaviour by sending SIGKILL to the parent process, which would leave the reader process spinning as described above.

Now we just need to find out which of the other 3 processes is dying and why.

**Comment by zsozso** [comment] 2015-03-05 17:44
Thank you for the fix, I'll try. 

After the restart I've got this. I've deleted the exact IP addresses:

.... (many lines)
greyd[25500]: deleting expired grey entry 94....
greyd[25500]: deleting expired grey entry 167....
greyd[25500]: deleting expired grey entry 167.....
greyd[25500]: deleting expired grey entry 198....
greyd[25500]: deleting expired grey entry 89....
Lock table is out of available lock entries
greyd[25500]: Error retrieving next record: Cannot allocate memory
greyd[25502]: stopping main process
greyd[25501]: stopping firewall process

**Comment by mikey-austin** [comment] 2015-03-05 22:48
Aha! It seems a child process (either the grey reader or grey updater processes) is exiting as the berkeley db locking limits have been reached (which is a fatal error). I believe the default number of Berkeley db locks is 1000, so you should definitely double it. Have a go placing the following in your /usr/local/var/greyd/DB_CONFIG file:

<pre>set_lk_max_locks   2000
set_lk_max_lockers 2000
set_lk_max_objects 2000</pre>

I think you may need to stop greyd/greylogd and do a *db_recover* in order to re-build the environment:

<pre># db_recover -cvh /usr/local/var/greyd/</pre>

For your environment you may want to tune it more finely:

http://docs.oracle.com/cd/E17076_02/html/programmer_reference/env_size.html

I will definitely add the ability to configure these berkeley db resources in the greyd.conf in the near future, as well as reporting on the existing limits with something like *greyd -V*.

**Comment by mikey-austin** [comment] 2015-03-12 02:15
Hi zsozso, did you try tuning your Berkeley DB? If so, how did it go? If it managed to solve your issues, I'd like to create some wiki pages with greyd performance tuning information.

**Comment by zsozso** [comment] 2015-03-16 20:25
Hi,

Unfortunately I didn't have  time to test :( 
There is something with "cleaning process" because when I blocked firewall after a big stress test (so no more traffic to greyd) and  after 6-8 hours later greyd exited. 
I guess in the meantime the greyd process tried to remove old entries from DB but that was'nt successfull. 
If you can you should take a look to those functions.

**Comment by mikey-austin** [comment] 2015-03-18 11:43
Ok great. I'll close this particular issue then.

**Closed by mikey-austin** 2015-03-18 11:43 UTC
Labels: bug
