### ISSUE TITLE
unexpected sqlite3_step result: 1

### ISSUE THREAD

**Issue by helioloureiro** [mikey-austin/greyd#9] opened 2016-07-08 13:17 UTC
Hi,

For every check on DB, I'm gettting back this error, like this, which failed on SPF verification:

Jul  8 10:14:04 server greyd[28591]: (GREY) 181.44.24.44: helio@loureiro.eng.br -> helio@loureiro.eng.br
Jul  8 10:14:04 server greyd[28592]: SPF failure for 181.44.24.44 helio@loureiro.eng.br helo cpe-181-44-24-44.telecentro-reversos.com.ar
Jul  8 10:14:04 server greyd[28592]: unexpected sqlite3_step result: 1

But it happens always.  I just added a few information for white and black domains using greydb -[TD] -a "@domain.com".  Since this message shows up 4 times in the source code, do you have any clue about could be the problem?

**Comment by mikey-austin** [comment] 2016-07-08 18:30
> For every check on DB, I'm gettting back this error, like this, which failed on SPF verification:
> 
> Jul 8 10:14:04 server greyd[28591]: (GREY) 181.44.24.44: helio@loureiro.eng.br -> helio@loureiro.eng.br
> Jul 8 10:14:04 server greyd[28592]: SPF failure for 181.44.24.44 helio@loureiro.eng.br helo cpe-181-44-24-44.telecentro-reversos.com.ar
> Jul 8 10:14:04 server greyd[28592]: unexpected sqlite3_step result: 1
> 
> But it happens always. I just added a few information for white and black domains using greydb -[TD] -a "@domain.com". 

After the SPF failure, grey.c starts a new db transaction and tries to do a db_get. It seems that for some reason (corruption maybe?), the get fails and the transaction is rolled back. This explains why the trap entry is never created (due to the SPF failure). Some things to check:

1. sqlite3 needs write permissions on the directory containing the database file (in addition to the db file itself) for doing transaction related operations. Does the greydb user have write permission on this directory?

2. Does everything look alright if you manually inspect (after stopping greyd) with the sqlite3 cli? Try with the greydb user, eg:

`$ sudo -u greydb sqlite3 /var/greyd/greyd.db`

try poking around the db to see if it is corrupted.

3. Try backing up the database and creating a new one, and see if this solves the issue.

> Since this message shows up 4 times in the source code, do you have any clue about could be the problem?

Yes, that message is not really helpful. I just pushed commit fea66a7e454 that will make it easier to see which function is reporting the error. Could you try this version?

It would be helpful if you could send me instructions on how to reproduce from a fresh greyd (including the greyd.conf). Or if you don't mind, you could send me your greyd.db.gz along with your greyd.conf and I would be happy to look at it.

**Comment by helioloureiro** [comment] 2016-11-03 20:53
Sorry for my very very very delayed response.  I really had no time to do that later and jut completely forgot it.

Well... let go to details.

After moronically trying your patches w/ no success, I just realized I cloned your project and my local git was pointing to... my outdated repository (duh!).  After fixed this, I synced git w/ your latest patches and started to dive in.

It showed a failed to write into db:

Nov  3 18:37:02 truta greyd[26169]: (GREY) 188.40.147.75: jeane.financeiro_4912043437@camw.com.br -> angelica@loureiro.eng.br
Nov  3 18:37:02 truta greyd[26170]: SPF passed for 188.40.147.75 jeane.financeiro_4912043437@camw.com.br helo egol1.camw.com.br
Nov  3 18:37:02 truta greyd[26170]: Mod_db_put: unexpected sqlite3_step result: 1
Nov  3 18:37:02 truta greyd[26169]: 188.40.147.75: disconnected after 31 seconds.

So I tried manually as greydb, and it did work.  But I tried as greyd and... it failed.

I changed db permission to 666 and now it is working just fine.  Meanwhile greylogd keeps track on it as greydb, greyd tries to write as greyd, which isn't allowed.

So far it is working w/ reads/writes for both greyd and greydb.  As much ugly as it can look w/ such permissions.

**Comment by mikey-austin** [comment] 2016-11-19 14:21
Ah, I think this is a permissions/ownership issue. greylogd should definitely be run as the greydb user.

See my config/permissions below and compare with yours:

```
[root@wynton greyd]# ll -d /var/empty/greyd
drwxr-x---. 2 greyd greyd 4096 Oct  5 04:46 /var/empty/greyd
[root@wynton greyd]# ll -d /var/empty/greylogd
drwxr-x---. 2 greydb greydb 4096 Oct  5 04:46 /var/empty/greylogd
[root@wynton greyd]# ll -d /var/lib/greyd
drwxr-x---. 2 greydb greydb 4096 Nov 20 00:51 /var/lib/greyd
[root@wynton greyd]# ll /var/lib/greyd/*.sqlite
-rw-r--r--. 1 greydb greydb 40960 Nov 20 00:51 /var/lib/greyd/greyd.sqlite
[root@wynton greyd]# grep ^user /etc/greyd/greyd.conf
user = "greyd"
[root@wynton greyd]# grep -A6 ^section\ grey /etc/greyd/greyd.conf
section grey {
    enable              = 1,
    user                = "greydb",
    traplist_name       = "greyd-greytrap",
    traplist_message    = "Your address %A has mailed to spamtraps here",
    whitelist_name      = "greyd-whitelist",
    whitelist_name_ipv6 = "greyd-whitelist-ipv6",
[root@wynton greyd]#
```

**Comment by mikey-austin** [comment] 2018-01-28 09:18
Closing as it is clear the database updating process was running as the wrong user _greyd_, as my last comment states.

**Closed by mikey-austin** 2018-01-28 09:18 UTC
